server:
  port: 7001
eureka:
  server:
    #取消eurekad的自我保护机制
    enable-self-preservation: false
  instance:
    hostname: eureka7001.com
  client:
    service-url:
      #      多个eureka互相注册
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false

