server:
  port: 7002
eureka:
  instance:
    hostname: eureka7002.com
  client:
    service-url:
#      多个eureka互相注册
      defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false
    fetch-registry: false